name: safeband_sos
description: "SafeBand SOS - Elderly emergency alert system connected to a Bluetooth wearable."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.22
  geolocator: ^13.0.0
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
